### ISSUE TITLE
User authentication 

### ISSUE THREAD

**Issue by Bensge** [RonMelkhior/ts3-viewer#1]
I tried this app but it's failing to get data from the server because, as far as I can see, it doesn't even try to register using a username / password pair. Is this WIP or did I miss something?

The log output:
```
[15-04 11:24:29] Now running
[15-04 11:24:30] Connected to the ServerQuery, getting data...
[15-04 11:24:30] Started HTTP server.
[15-04 11:24:30] [object Object]
(node:67515) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'filter' of undefined
(node:67515) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[15-04 11:24:31] [object Object]
(node:67515) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'filter' of undefined
and so on...
```

**Comment by RonMelkhior** [comment]
I didn't add a login option (per-environment) yet, although the method for it exists.

You can simply add the permissions required for `channellist` & `clientlist` to the Guest server-group.

For `channellist`:  
- `b_virtualserver_channel_list`

For `clientlist`:  
- `b_virtualserver_client_list`
- `i_channel_subscribe_power`
- `i_channel_needed_subscribe_power`

**Comment by Bensge** [comment]
Okay thanks. I guess that works for now, but in the long term I wouldn't want to expose that information to unregistered users. I'll take a shot at the login code, if you have any pointers that'd be cool

**Comment by RonMelkhior** [comment]
https://github.com/RonMelkhior/ts3-viewer/blob/master/src/viewer/index.js#L45

Before running `.use`, run `.login`.

```js
onReady(prompt) {
    this.ts3.login('user', 'pass')
    .then(res => {
        this.ts3.use(this.serverID)
        .then(response => this.emit('ready', prompt))
        .catch(error => this.emit('error', error));
    })
    .catch(error => this.emit('error', error));
}
```

**Comment by Bensge** [comment]
That works, thanks!

**Comment by RonMelkhior** [comment]
Added this as a built-in option in c4ee3ad.
