### ISSUE TITLE
Timeout handling

### ISSUE THREAD

**Issue by RonMelkhior** [RonMelkhior/ts3-viewer#3]
At the moment, if the viewer loses connection to the TS3 ServerQuery, it doesn't attempt to reconnect back.

**Comment by ericadamski** [comment]
@RonMelkhior this is my first time contributing to OSS, could you point me in the right direction for this?

**Comment by RonMelkhior** [comment]
Hey @ericadamski, of course.  
I'll go over this in the hierarchy of the application.

First and foremost, the connection is handled by the `Query` class ([here](https://github.com/RonMelkhior/ts3-viewer/blob/master/src/query/Query.js)) in the constructor.

My `TeamspeakFramework` class ([here](https://github.com/RonMelkhior/ts3-viewer/blob/master/src/query/index.js)) handles the server connection in the constructor as you can see, by initializing a 

`TeamspeakFramework` is initialized by my `Viewer` class ([here](https://github.com/RonMelkhior/ts3-viewer/blob/master/src/viewer/index.js)), in the constructor.

The most optimal way to fix this would be to create a `connect()` in `Query` which would initialize the connection (same way as in the constructor, perhaps even let the constructor call it in order to not duplicate code), and call it from `Viewer` in `onTimeout()` or `onClose()` (which are already present!)

**Comment by ericadamski** [comment]
@RonMelkhior sounds great I will give this a go!

**Comment by ericadamski** [comment]
@RonMelkhior one more question for you, how would I go about testing this?

**Comment by ericadamski** [comment]
@RonMelkhior I also cannot push to your repo. I created a branch for this change, could you allow me to push and I will open a PR. 😄

**Comment by RonMelkhior** [comment]
@ericadamski 

Here's an example `.env` to test it out:

```
TEAMSPEAK_QUERY_HOST=voice.panda-community.com
TEAMSPEAK_QUERY_PORT=10011
TEAMSPEAK_QUERY_LOGIN=false
TEAMSPEAK_QUERY_USER=admin
TEAMSPEAK_QUERY_PASS=foobar
TEAMSPEAK_QUERY_SERVER_ID=4
```

To test a time-out, try to block the connection via your firewall etc.

---

And in order to send a PR, please fork the repository and then push your changes to your own repo, then you can submit a PR easily.

**Comment by ericadamski** [comment]
I am trying to run using the config you sent, I haven't changed anything yet, this what I am seeing, is it normal?
![screen shot 2017-10-02 at 9 33 34 am](https://user-images.githubusercontent.com/6516758/31079812-e1a44ca2-a754-11e7-89c0-2c6b8b22521b.png)

**Comment by RonMelkhior** [comment]
Yes, that is how it should look. Now go to `localhost` (with whatever port is in `.env`) and you'll see.
