### ISSUE TITLE
cspacer issue

### ISSUE THREAD

**Issue by HaLuZaR** [RonMelkhior/ts3-viewer#6]
Hi, when channel has spacer like this - "[*cspacer11]—" web will display just — I would like to ask you, Is It possible to make it fullwidth line? 

offtopic: this app is super cool, i really like it, thanks for that :) big up

Thanks

**Comment by RonMelkhior** [comment]
Hi, this is a bug with the way I parse spacers.

**Comment by RonMelkhior** [comment]
Fixed in b1ea92ac4.

Right now though, it will not make it a "full-width" line, since the name repetition is handled server-side.  
I might fix it and make it client-side to have the full effect, but no guarantees.
